baseURL = "https://sketches.lethain.com"
languageCode = "en-us"
title = "Exuberant Sketches"
copyright = "Will Larson"
theme = "ananke"
paginate = 1000
[author]
    name = "Will Larson"
[params]
  mainSections = ["meta", "books", "posts"]
[menu]
  [[menu.main]]
    name = "Staff Engineer"
    url = "https://staffeng.com"
  [[menu.main]]
    name = "An Elegant Puzzle"
    url = "https://lethain.com/elegant-puzzle/"
  [[menu.main]]
    name = "Irrational Exuberance"
    url = "https://lethain.com"
  [[menu.main]]
    weight = 100
    name = "About"
    url = "/misc/about"

